### ISSUE TITLE
Error: A value of type 'TextStyle?' can't be assigned to a variable of type 'TextStyle'

### ISSUE THREAD

**Issue by ozkayas** [artflutter/flutter_awesome_select#11]
Facing this issue after upgrading to Flutter 2.10.0

Error: A value of type 'TextStyle?' can't be assigned to a variable of type 'TextStyle' because 'TextStyle?' is nullable and 'TextStyle' isn't.
 - 'TextStyle' is from 'package:flutter/src/painting/text_style.dart' ('../../Development/flutter/packages/flutter/lib/src/painting/text_style.dart').
    final TextStyle defaultLabelStyle = ChipTheme.of(context).labelStyle;

**Comment by vasilich6107** [comment]
Ho
@ozkayas @masterix21 
Will take a look at the issues this week

**Comment by petodavid** [comment]
Same issue here, any fix?

**Comment by vasilich6107** [comment]
check flutter_awesome_select 6.1.2-beta

**Comment by vital487** [comment]
This saved me, thanks

**Comment by chrisvidal** [comment]
thanks :)

**Comment by vasilich6107** [comment]
As far as I see positive feedbacks - closing the issue
