### ISSUE TITLE
Flutter 3.0 support

### ISSUE THREAD

**Issue by hs029** [artflutter/flutter_awesome_select#15]
See this:

../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_awesome_select-6.1.2-beta/lib/src/widget.dart:1550:58: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/widgets/binding.dart').
                MediaQueryData.fromWindow(WidgetsBinding.instance!.window);
                                                         ^
../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_awesome_select-6.1.2-beta/lib/src/text_error.dart:99:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_awesome_select-6.1.2-beta/lib/src/modal.dart:41:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) => widget.onReady.call());

**Comment by shep920** [comment]
+1

**Comment by vasilich6107** [comment]
@hs029 @shep920 
check flutter_awesome_select 6.2.0-beta
