### ISSUE TITLE
Unexpected null value when using chips

### ISSUE THREAD

**Issue by mapariumdevteam** [artflutter/flutter_awesome_select#17]
Flutter 3.0.1
run on chrome
Chips gives error.

**Comment by vasilich6107** [comment]
@mapariumdevteam could you provide an example which can be copy pasted and tested

**Comment by mapariumdevteam** [comment]
I just clone the repo and use flutter run -d chrome command under example folder. all interface and lib run without any error. But when i click the Chips sample it gives this error.

**Comment by vasilich6107** [comment]
Ok, will check

**Comment by gliitterpuke** [comment]
following up! --same issue

**Comment by vasilich6107** [comment]
fixed in  flutter_awesome_select 6.4.0
