### ISSUE TITLE
Chip delete keep standing in UI

### ISSUE THREAD

**Issue by Bockos** [artflutter/flutter_awesome_select#2]
Hi,

The delete property in the "S2Tile.fromState > body" section is working but the selected property keep standing in the screen. I mean it works in backend, but UI does not change. How can I fix that problem?
 Please consider the picture below. 

When I check your examples, it also occurs in there.

My delete code;
chipOnDelete: (i) {
setState(() => groupedBusinessListSelected
.remove(state.selected!.choice![i].value));

![image](https://user-images.githubusercontent.com/23163077/141974999-7a4227a4-b3b5-4e88-95ed-fd04ddaeaec1.png)

**Comment by vasilich6107** [comment]
Hi @Bockos did you check the `example` project?
Do you see the same error there?

**Comment by Bockos** [comment]
Hello @vasilich6107,  

Yes, unfortunately the same error also exist in your example.
You can refer "Customize Modal > Choice Selector > Phones" example.
Try to delete selected value and u will see it will keep standing.

**Comment by vasilich6107** [comment]
Thanks @Bockos I will check

**Comment by Bockos** [comment]
@vasilich6107  did u check? 
Let me know if the new version will release or not in nowadays?

Thanks

**Comment by vasilich6107** [comment]
Hi @Bockos i did check
The bug definitely exists
If I fill not fix it today - I will make another atempt in 10 day due to vacation

**Comment by vasilich6107** [comment]
@Bockos 
check flutter_awesome_select 6.0.1

**Comment by Bockos** [comment]
Excellent job @vasilich6107 
Works fine! thanks.
