### ISSUE TITLE
Can't seem to add this package into project

### ISSUE THREAD

**Issue by RayBrimstone** [artflutter/flutter_awesome_select#6]
Hello, i got the following message when i was trying to add this package to my project:

`flutter pub add flutter_awesome_select
Resolving dependencies...
  async 2.5.0 (2.8.2 available)
  characters 1.1.0 (1.2.0 available)
  charcode 1.2.0 (1.3.1 available)
+ flutter_awesome_select 6.0.1
  horizontal_data_table 3.5.0 (3.6.0 available)
  http 0.13.3 (0.13.4 available)
  js 0.6.3 (0.6.4 available)
  matcher 0.12.10 (0.12.11 available)
  meta 1.3.0 (1.7.0 available)
  path 1.8.0 (1.8.1 available)
  path_provider 2.0.4 (2.0.8 available)
  path_provider_linux 2.1.2 (2.1.5 available)
  path_provider_macos 2.0.3 (2.0.5 available)
  path_provider_platform_interface 2.0.1 (2.0.3 available)
  path_provider_windows 2.0.4 (2.0.5 available)
  pedantic 1.11.1 (discontinued replaced by lints)
  platform 3.0.2 (3.1.0 available)
  plugin_platform_interface 2.0.2 (2.1.2 available)
  process 4.2.3 (4.2.4 available)
  provider 6.0.1 (6.0.2 available)
  shared_preferences 2.0.7 (2.0.12 available)
  shared_preferences_linux 2.0.3 (2.0.4 available)
  shared_preferences_web 2.0.2 (2.0.3 available)
  shared_preferences_windows 2.0.3 (2.0.4 available)
  source_span 1.8.0 (1.8.1 available)
  sqflite 2.0.0+4 (2.0.1 available)
  sqflite_common 2.0.1+1 (2.2.0 available)
  syncfusion_flutter_core 19.3.55 (19.4.42 available)
  syncfusion_flutter_datepicker 19.3.55 (19.4.42 available)
  test_api 0.2.19 (0.4.9 available)
  vector_math 2.1.0 (2.1.1 available)
  win32 2.0.5 (2.3.3 available)
**Downloading flutter_awesome_select 6.0.1...
Could not decompress gz stream Connection closed while receiving data, path = ''
pub finished with exit code 66`**

Flutter Doctor:
`flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.1415], locale en-MY)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] Connected device (3 available)

• No issues found!`

Anyone knows what seems to be the problem here?

**Comment by vasilich6107** [comment]
@RayBrimstone try 6.1.1-beta

I released the package with `pub publish` so I do not know what causes the issue on your side

**Comment by RayBrimstone** [comment]
Hello i tried again today and it's working. Thank you for the help @vasilich6107
