### ISSUE TITLE
Migration trouble from smart_select

### ISSUE THREAD

**Issue by ozkayas** [artflutter/flutter_awesome_select#7]
Hi,
I am trying to migrate our project from smart_select 4.3.2 to flutter_awesome_select 6.0.0
However I can not figure what to use at some points, for example:
old code was using `value` property but new library does not have this. For example:

**Smart Select 4.3.2** 
```
class S2SingleState<T> extends S2State<T> {

  /// value changes state
  @override
  S2SingleChanges<T> changes;

  /// final value
  @override
  T value;
```
**flutter_awesome_select:**
```
class S2SingleState<T> extends S2State<T> {
  /// State of the selected choice(s)
  @override
  S2SingleSelected<T>? selected;

  /// State of choice(s) selection in the modal
  @override
  S2SingleSelection<T>? selection;
```
Is there any migration documentation? Or any direction I can follow?
Thanks in advance.

**Comment by vasilich6107** [comment]
Hi @ozkayas is forked the package from original repo
and there is no `value` on master branch
https://github.com/davigmacode/flutter_smart_select/blob/master/lib/src/widget.dart#L1679

**Comment by ozkayas** [comment]
Thanks @vasilich6107 
Hmm.. Maybe our version was an older one 🤔
Anyway, I've just found that I should use `value` property of `S2SingleSelected` class.
If anyone comes here for the same issue :)

**Comment by vasilich6107** [comment]
@ozkayas thanks for explanation
closing the issue
