### ISSUE TITLE
A value of type 'Color?' can't be assigned to a variable of type 'Color'

### ISSUE THREAD

**Issue by jsml** [artflutter/flutter_awesome_select#9]
chip_theme.dart

After upgrading flutter 2.8.1 to 2.10.0

This error occured

**Comment by youannis-aziz** [comment]
same issue

**Comment by youannis-aziz** [comment]
^
    /development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_awesome_select-6.1.1-beta/lib/src/chip_theme.dart:61:38: Error: A value of type 'Color?' can't be assigned to a variable of type 'Color' because 'Color?' is nullable and 'Color' isn't.
     - 'Color' is from 'dart:ui'.
        final Color primaryColor = color ??
                                         ^
    /development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_awesome_select-6.1.1-beta/lib/src/chip_theme.dart:85:63: Error: A value of type 'TextStyle?' can't be assigned to a variable of type 'TextStyle' because 'TextStyle?' is nullable and 'TextStyle' isn't.

**Comment by youannis-aziz** [comment]
```
    /development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_awesome_select-6.1.1-beta/lib/src/chip_theme.dart:61:38: Error: A value of type 'Color?' can't be assigned to a variable of type 'Color' because 'Color?' is nullable and 'Color' isn't.
     - 'Color' is from 'dart:ui'.
        final Color primaryColor = color ??
                                         ^
    /development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_awesome_select-6.1.1-beta/lib/src/chip_theme.dart:85:63: Error: A value of type 'TextStyle?' can't be assigned to a variable of type 'TextStyle' because 'TextStyle?' is nullable and 'TextStyle' isn't.
     - 'TextStyle' is from 'package:flutter/src/painting/text_style.dart' ('/development/flutter/packages/flutter/lib/src/painting/text_style.dart').
        final TextStyle defaultLabelStyle = ChipTheme.of(context).labelStyle;
                                                                  ^

```

**Comment by petodavid** [comment]
Same issue here

**Comment by jsml** [comment]
I had fixed myself

**Comment by petodavid** [comment]
How?

**Comment by jsml** [comment]
Use patched 
https://github.com/jsml/flutter_awesome_select/tree/patch-1

I had committed 
https://github.com/jsml/flutter_awesome_select/commit/4be93c4a845b1023166e9f1bd79107b07f9865e3
